name: Bug Report
description: Report a bug in the Membershiping Inventory & Trading System
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: input
    id: wordpress-version
    attributes:
      label: WordPress Version
      placeholder: e.g. 6.4.2
    validations:
      required: true

  - type: input
    id: woocommerce-version
    attributes:
      label: WooCommerce Version
      placeholder: e.g. 8.5.0
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: e.g. 8.1.0
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including error messages, screenshots, etc.
